version: '3.8'

services:
  backend:
    image: harry1019/canvasserver:latest
    container_name: canvaserver
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    image: harry1019/canvaswebsite:latest
    container_name: canvaswebsite
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
